apiVersion: apps/v1
kind: Deployment
matadata: 
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas}}
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    matadata:
    labels:
      app: guestbook-frontend
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
