apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.svcname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: guestbook-frontend
spec:
  selector:
    app: guestbook-frontend
  ports:
    - name: {{ .Values.frontend.svcport-name }}
      port: {{ .Values.frontend.svcport }}      # 8080
      targetPort: {{ .Values.frontend.targetPort }}  #8080
  type: {{ .Values.frontend.svctype }} 

