apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas}}
  selector:
    matchLabels:
      app: guestbook-frontend
  template:
    metadata:
      labels:
        app: guestbook-frontend
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          volumeMounts:
            - name: {{ .Values.frontend.cmname}}
              mountPath: {{ .Values.frontend.cmPath}}
              subPath: {{ .Values.frontend.cmsubPath}}
      volumes:
        - name: {{ .Values.frontend.cmname}}
          configMap:
            name: {{ .Values.frontend.name }}-config
