apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.postgres.name }}
  namespace: {{ .Values.namespace }}  
spec:
  replicas: {{ .Values.postgres.replicas}}
  minReadySeconds: {{ .Values.postgres.minReadySeconds}}
  serviceName: {{ .Values.postgres.svcname}}
  selector: 
    matchLabels:
      app: guestbook-postgres
  template:
    metadata:
      labels:
        app: guestbook-postgres
    spec:
      terminationGracePeriodSeconds: {{ .Values.postgres.terminationGracePeriodSeconds}}   # 30-60 sec?
      containers:
        - name: {{ .Values.postgres.name }}
          env:
            - name: POSTGRESQL_USER
              value: {{ .Values.postgres.user }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgres.database }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRESQL_PASSWORD    #need to create a secrets in cluster


          image: {{ .Values.postgres.image }} 
          ports:
          - containerPort: {{ .Values.postgres.containerPort }} 
            name: {{ .Values.postgres.name }}
          volumeMounts:
          - name: {{ .Values.postgres.storagename }}  
            mountPath:  {{ .Values.postgres.mountPath }}       # /var/lib/pgsql/data
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.postgres.storagename }}
    spec:
      accessModes: 
        - {{ .Values.postgres.accessModes }}
      storageClassName: {{ .Values.postgres.storageClassName}}
      resources:
        requests:
          storage: {{ .Values.postgres.storageSize}}
