apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.svcname }}
  labels:
    app: guestbook-postgres
spec:
  ports:
  - port: {{ .Values.postgres.svcport }}
    name: {{ .Values.postgres.svcportname }}
  clusterIP: None                      # headless svc for statefulset
  selector:
    app: guestbook-postgres