apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  namespace: {{ .Values.namespace }} 
spec:
  replicas: {{ .Values.redis.replicas}}
  selector:
    matchLabels:
      app: guestbook-redis
  template:
    metadata:
      labels:
        app: guestbook-redis
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.imagePullPolicy }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD              

          ports:
            - containerPort: {{ .Values.redis.containerPort }}
